version: "3"

services:
  redis-persistent:
    image: redis:alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-persistent.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  redis-inmemory:
    image: redis:alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-inmemory.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"