version: "3"

services:
  beanstalkd-persistent:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"
    volumes:
      - "./beanstalkd.conf:/etc/conf.d/beanstalkd"
      - "./beanstalkd-persistent.sh:/etc/init.d/beanstalkd"

  beanstalkd-inmemory:
    image: schickling/beanstalkd
    ports:
      - "11301:11300"
    volumes:
      - "./beanstalkd.conf:/etc/conf.d/beanstalkd"
      - "./beanstalkd-inmemory.sh:/etc/init.d/beanstalkd"

  beanstalkd-console:
    image: schickling/beanstalkd-console
    ports:
      - "2080:2080"
    links:
      - beanstalkd-persistent:beanstalkd-persistent
      - beanstalkd-inmemory:beanstalkd-inmemory