language: csharp
dist: xenial
sudo: required
solution: Homework.Dotnet.Tasks.sln
mono: none
dotnet: 5.0

script:
 - dotnet --info
 - dotnet restore
 - dotnet build
 - dotnet test ./tests/Homework.Dotnet.Tasks.Unit.Tests/Homework.Dotnet.Tasks.Unit.Tests.csproj