version: '3.8'
services:

  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password123"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: