version: '3'
services:
  nginx-images: 
    image: nginx:latest
    container_name: nginx-images
    volumes:
      - ./nginx/nginx-images.conf:/etc/nginx/nginx.conf
      - ./images:/data/images
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    ports:
      - 8080:80

  nginx-cache:
    image: openresty/openresty:alpine-fat
    container_name: nginx-cache
    volumes:
      - ./nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/lua:/lua
      - ./cache:/data/nginx/cache
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    links:
      - nginx-images  
    ports:
      - 8081:80