version: '3'
services:
  cdn-node:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/lua:/lua
    ports:
      - "80"
    depends_on:
      - source

  cdn-balancer:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-balancer.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - cdn-node

  source:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-images.conf:/etc/nginx/nginx.conf
      - ./images:/data/images
    ports:
      - "80"